### ISSUE TITLE
Error when trying to initialize database

### ISSUE THREAD

**Issue by exothermix** [alibaba/easydispatch#5]
when using the command "python -m dispatch.cli database init"  with the latest commit I get the error:-

Failed to load tables ... Ignore this if you are creating database ...
_get_workers failure,msg=(psycopg2.errors.UndefinedTable) relation "dispatch_core.organization" does not exist
LINE 2: FROM dispatch_core.organization
             ^

[SQL: SELECT dispatch_core.organization.id AS dispatch_core_organization_id, dispatch_core.organization.code AS dispatch_core_organization_code, dispatch_core.organization.callback_url AS dispatch_core_organization_callback_url, dispatch_core.organization.max_nbr_jobs AS dispatch_core_organization_max_nbr_jobs, dispatch_core.organization.max_nbr_teams AS dispatch_core_organization_max_nbr_teams, dispatch_core.organization.max_nbr_workers AS dispatch_core_organization_max_nbr_workers, dispatch_core.organization.team_flex_form_schema AS dispatch_core_organization_team_flex_form_schema, dispatch_core.organization.worker_flex_form_schema AS dispatch_core_organization_worker_flex_form_schema, dispatch_core.organization.job_flex_form_schema AS dispatch_core_organization_job_flex_form_schema, dispatch_core.organization.zulip_is_active AS dispatch_core_organization_zulip_is_active, dispatch_core.organization.zulip_site AS dispatch_core_organization_zulip_site, dispatch_core.organization.zulip_user_name AS dispatch_core_organization_zulip_user_name, dispatch_core.organization.zulip_password AS dispatch_core_organization_zulip_password, dispatch_core.organization.public_registration AS dispatch_core_organization_public_registration, dispatch_core.organization.created_at AS dispatch_core_organization_created_at, dispatch_core.organization.updated_at AS dispatch_core_organization_updated_at, dispatch_core.organization.updated_by AS dispatch_core_organization_updated_by 
FROM dispatch_core.organization]
(Background on this error at: http://sqlalche.me/e/13/f405)
Usage: cli.py database [OPTIONS] COMMAND [ARGS]...
Try 'cli.py database --help' for help.

Error: No such command 'init'.

**Comment by qiyangduan** [comment]
It was identified as a bug, sorry for this.
It has been fixed in commit [b3e999f](https://github.com/alibaba/easydispatch/commit/b3e999f5d7dc09e00ee87e43ec15c3257063f451)

please use the latest master containing this fix.

**Comment by qiyangduan** [comment]
I will close this issue next week if no further questions. Thanks.

**Comment by qiyangduan** [comment]
closed as fixed.
